### ISSUE TITLE
Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by FelixKLG** [johnpapa/vscode-cloak#55]
Cloak does not work on MacOS (M1), I have not tested Cloak on other operating systems however when I try to use it; it does not work.

The Cloak 'Output' tab in VSC says 'Cloak is initialised.' but when I try to enable cloak it does nothing, when I use the Cloak button in the bottom bar I get the error from the issue title.

Additionally in the VSC 'Extension Host' output tab I see:

```
2023-02-12 17:06:43.188 [error] TypeError: Cannot read properties of undefined (reading 'includes')
    at /Users/felixklg/.vscode/extensions/johnpapa.vscode-cloak-0.5.0/dist/extension.js:1:5610
    at Array.find (<anonymous>)
    at /Users/felixklg/.vscode/extensions/johnpapa.vscode-cloak-0.5.0/dist/extension.js:1:5595
    at /Users/felixklg/.vscode/extensions/johnpapa.vscode-cloak-0.5.0/dist/extension.js:1:5660
    at Generator.next (<anonymous>)
    at /Users/felixklg/.vscode/extensions/johnpapa.vscode-cloak-0.5.0/dist/extension.js:1:4306
    at new Promise (<anonymous>)
    at o (/Users/felixklg/.vscode/extensions/johnpapa.vscode-cloak-0.5.0/dist/extension.js:1:4051)
    at t.toggleSecretsHandler (/Users/felixklg/.vscode/extensions/johnpapa.vscode-cloak-0.5.0/dist/extension.js:1:5454)
    at s.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108016)
    at s.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108744)
    at l.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11239)
    at l.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10957)
    at l.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10044)
    at l.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9022)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:7810
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:13941)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) cloak.toggleSecrets {"value":"johnpapa.vscode-cloak","c":"johnpapa.vscode-cloak"}
```

**Comment by johnpapa** [comment]
Final clarification with thanks: this duplicate maps to the same includes crash tracked in #61.
